### PR TITLE
Update to .Net Core 3.1

### PR DESCRIPTION
**Pull request by tomasiewicz-dominik**
The version 2.0 is not worked for me on azure so I updated the version in csproj and examples stared working as expected

### CODE REVIEW

**Comment by ChrisAcrobat** [comment]
Thanks. I also had this problem, this fixed it. @MicrosoftDocs please update.

**Comment by sieldev** [comment]
Got same error practising on microsoft learning (module: Implement message-based communication workflows with Azure Service Bus)
Please accept and merge this commit :)

**Comment by V-Suzly** [comment]
#sign-off

**Review by V-Suzly — APPROVED** [review]
The product changed the information is correct.

**Comment by V-Suzly** [comment]
fixes AB#352641

**Comment by kimsey0** [comment]
Fixed by #8.

**Comment by tomasiewicz-dominik** [comment]
Closing this PR, already fixed in #8

**Pull request closed without merging**
